version: "2.3"
services:
  database:
    image: quay.io/azavea/postgis:2.4-postgres10.9-slim
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "district_builder"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  server:
    image: node:10-stretch
    env_file: .env
    environment:
      - CI
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3005:3005
    links:
      - database:database.service.districtbuilder.internal
    volumes:
      - ./:/opt/db2/
    working_dir: /opt/db2/src/server
    command: yarn run start:dev

  client:
    image: node:10-stretch
    env_file: .env
    environment:
      - CI
    ports:
      - 3003:3003
    links:
      - server:backend.service.districtbuilder.internal
    volumes:
      - ./:/opt/db2/
    working_dir: /opt/db2
    command: yarn run start
